// All page copy, English and Spanish. Spanish copy needs native speaker review before launch.
export type Lang = "en" | "es";
export type Variant = "a" | "b" | "c";

const en = {
  meta: {
    title: "Hoys for Pros: same hours, more paid jobs",
    desc: "Paid jobs with no lead fees, plus a crew that handles office work by text or voice in 30+ languages.",
  },
  top: { textUs: "Text us", langLabel: "Language" },
  hero: {
    h1: {
      a: "Paid jobs. No lead fees.",
      b: "Paid jobs. No lead fees.",
      c: "Paid jobs. No lead fees.",
    },
    sub: "Customers pay first. Hoys handles office work by text or voice in 30+ languages.",
    chipTitle: "New paid job: AC tune-up",
    chipSub: "Thu 10 AM. You take home $255.",
    artAlt: "Riso illustration of a home service pro at work",
  },
  cta: "Join the waitlist",
  example: "EXAMPLE",
  live: {
    remaining: (n: number) =>
      n > 0 ? `Only ${n} spots left.` : "This group is full. Join for the next rollout.",
    left: (n: number, c: string) => `${n} spots left in ${c}.`,
  },
  trust: {
    teamLabel: "Team from",
    teamNames: ["Meta", "Google", "Amazon"],
    backedLabel: "Backed by leaders at",
    backedNames: ["Snap", "Meta", "Google"],
    aria: "See who is behind Hoys",
  },
  pain: {
    h2: "Sound familiar?",
    items: [
      "Paying for leads that never call back.",
      "Quotes and invoices at 10 PM.",
      "Chasing customers to get paid.",
    ],
    fix: "Hoys fixes all three.",
  },
  two: {
    h2: "Hoys does two things for you.",
    paidLabel: "Paid jobs",
    paidH3: "Jobs that are already paid for.",
    paidList: [
      "The customer pays before you show up.",
      "One pro per job. You never pay for a lead.",
      "You see your take-home, then take it or pass.",
    ],
    admit: "ADMIT ONE PRO",
    crewLabel: "AI crew",
    crewH3: "Help with the office work, by text or voice.",
    crewList: [
      "Answers when you cannot and books the work.",
      "Prepares quotes from photos, moves your day and orders parts.",
      "Sends invoices and follows up on money owed—in 30+ languages.",
    ],
    note: "Works on the customers you already have.",
    noteFree: " No charge on your own jobs.",
  },
  day: {
    h2: "A day with Hoys",
    sub: "Text or talk to it like someone on your crew. It handles the rest.",
    biz: "AI crew for Ramos Heating and Air",
    you: "You",
    replay: "Replay",
    roles: ["Answers", "Quotes", "Gets parts", "Finds jobs", "Reschedules", "Follows up"],
    msgs: {
      m1: "Morning! You've got 4 jobs today. First stop is Maple St at 8. I'll text you the address.",
      m2: "Dana on Alder St needs her AC checked. It's not cooling. She's free at 3. Want me to book her in?",
      m3: "Book it",
      s3: "BOOKED 3 PM",
      m4: "What's next?",
      m5: "Maple St, furnace won't start. They sent photos—could be the igniter. Want me to check if the supply house has one?",
      m6: "Yes",
      s6: "IN STOCK · HELD FOR PICKUP",
      m7: "You've got a gap at 1. AC tune-up, 2 miles away. Customer paid $300. Your take-home is $255. Want it?",
      m8: "Take it",
      s8: "PAID JOB BOOKED",
      m9: "Running long. Push everything an hour.",
      m10: "All set. Tune-up at 2, Dana at 4. Both said that works. I'll send the addresses when you're ready.",
      m11: "Invoices are out. I nudged the Johnsons about the $180. You're done for today—I'll send tomorrow's jobs in the morning.",
      s11: "INVOICES SENT",
    },
  },
  paid: {
    h2: "Paid jobs, not paid leads.",
    rate: "Commission starts at 15%. You see the exact amount before you accept.",
    job: "AC tune-up",
    when: "Thu 10 AM, 2 miles away",
    r1: "Customer paid first",
    r2: "Hoys keeps (starts at 15%)",
    tot: "You take home",
    take: "TAKE IT",
    pass: "PASS, NO COST",
    cmpL: "Lead sites",
    cmpR: "Hoys",
    rows: [
      ["$35 to $200+ per lead", "$0 upfront"],
      ["Same lead sent to several pros", "One pro per job"],
      ["Most never reply", "Customer already paid"],
      ["You pay, win or lose", "From 15%, only on completed jobs"],
    ],
    whereQ: "Where do paid jobs come from?",
    whereA:
      "More people now ask AI assistants to get things fixed at home. When they do, Hoys books a nearby pro, takes the payment first and holds it until the job is done.",
  },
  how: {
    h2: "How it works",
    steps: [
      ["Join the waitlist", "Tell us where you work and what you do."],
      ["Set up by text", "About 15 minutes when your area opens."],
      ["The AI crew starts. Paid jobs follow.", "Founding pros get paid jobs first."],
    ],
  },
  team: {
    h2: "Who is behind Hoys",
    rishiRole: "Co-founder and CEO",
    rishi:
      "Built Asia's largest tech platform for small store owners: 100,000+ shops. Backed by top investors and founders of DoorDash and Zoom.",
    satwikRole: "Co-founder and CTO",
    satwik:
      "Built AI systems at Meta (Facebook). PhD from Carnegie Mellon. Previously worked at Google.",
  },
  spots: {
    h2: "Founding spots are limited.",
    sub: "Paid jobs open city by city. Founding pros get them first.",
    taken: (t: number, c: number) => `${t} of ${c} taken`,
    joined: (n: number) => `${n} pros joined`,
    full: "WAITLIST ONLY",
    next: "Join for the next group.",
    recent: "Recent joins",
    when: { today: "today", yesterday: "yesterday", "this week": "this week" },
    defaultTrade: "Home service pro",
  },
  cities: {
    bay_area: "Bay Area",
    los_angeles: "Los Angeles",
    new_york: "New York",
    other: "Somewhere else",
  },
  citiesShort: {
    bay_area: "the Bay Area",
    los_angeles: "LA",
    new_york: "New York",
    other: "your area",
  },
  final: { h2: "Paid jobs and an AI crew. Free to join." },
  footer: { questions: "Questions?", text: "Text" },
  sheet: {
    workOrder: "WORK ORDER",
    close: "Close",
    h: "Join the waitlist",
    hSub: "Paid jobs with no lead fees.",
    where: "Where do you work?",
    name: "Your name",
    namePh: "First and last name",
    phone: "Mobile number",
    otherCity: "Your city",
    otherCityPh: "City, state",
    consentBold: "I agree Hoys may text or call me about the waitlist.",
    saving: "Saving...",
    errCity: "Pick where you work.",
    errName: "Add your name.",
    errPhone: "That number does not look right.",
    errOtherCity: "Add the city where you work.",
    errConsent: "Check the box so we can text you.",
    errNet: "That did not go through. Check your signal and try again.",
    s2h: "One last step.",
    s2sub: "Tell us what kind of work you do, then join the list.",
    trades: "Your trades",
    tradeLabels: {
      plumbing: "Plumbing",
      electrical: "Electrical",
      hvac: "HVAC",
      handyman: "Handyman",
      roofing: "Roofing",
      general_contractor: "General contractor",
      cleaning: "Cleaning",
      other: "Other",
    },
    whichTrade: "Which trade?",
    crew: "Crew size",
    crewLabels: {
      just_me: "Just me",
      "2_5": "2 to 5",
      "6_10": "6 to 10",
      "10_plus": "More than 10",
    },
    zip: "Zip code",
    biz: "Business name (optional)",
    email: "Email (optional)",
    errZip: "Zip codes have 5 digits.",
    errEmail: "That email does not look right.",
    save: "Join the waitlist",
    onList: "ON THE LIST",
    inCity: (c: string) => `in ${c}`,
    onTheList: "on the list",
    step1: "We text you to confirm.",
    step2: (c: string) => `When ${c} opens, we set you up by text. About 15 minutes.`,
    step3: "Founding pros get paid jobs first.",
    knowPro: "Know a pro tired of paying for leads?",
    share: "Share link",
    copy: "Copy link",
    copied: "Copied",
    shareText: "Hoys sends paid jobs to pros. No lead fees. Join the waitlist:",
    bump: (n: number) => `Each pro who joins with your link moves you up ${n} spots.`,
    call: "Want a quick call with our team?",
    callBtn: "Yes, call me",
    callDone: "Done. Someone from Hoys will call you.",
  },
  // Exact consent text stored with each signup, in the language shown.
  consentText: "Hoys can text or call me about the waitlist.",
};

export type Dict = typeof en;

const es: Dict = {
  meta: {
    title: "Hoys para Pros: mismas horas, más trabajos pagados",
    desc: "Trabajos pagados sin pagar por leads, más ayuda con la oficina por texto o voz en más de 30 idiomas.",
  },
  top: { textUs: "Escríbenos", langLabel: "Idioma" },
  hero: {
    h1: {
      a: "Trabajos pagados. Sin pagar por leads.",
      b: "Trabajos pagados. Sin pagar por leads.",
      c: "Trabajos pagados. Sin pagar por leads.",
    },
    sub: "El cliente paga primero. Hoys se encarga de la oficina por texto o voz en más de 30 idiomas.",
    chipTitle: "Nuevo trabajo pagado: mantenimiento de AC",
    chipSub: "Jue 10 AM. Te llevas $255.",
    artAlt: "Ilustración de un pro de servicios del hogar trabajando",
  },
  cta: "Únete a la lista",
  example: "EJEMPLO",
  live: {
    remaining: (n: number) =>
      n > 0
        ? `Solo quedan ${n} lugares.`
        : "Este grupo está lleno. Únete para la próxima apertura.",
    left: (n: number, c: string) => `Quedan ${n} lugares en ${c}.`,
  },
  trust: {
    teamLabel: "Equipo de",
    teamNames: ["Meta", "Google", "Amazon"],
    backedLabel: "Respaldado por líderes en",
    backedNames: ["Snap", "Meta", "Google"],
    aria: "Mira quién está detrás de Hoys",
  },
  pain: {
    h2: "¿Te suena?",
    items: [
      "Pagar por leads que nunca te contestan.",
      "Cotizaciones y facturas a las 10 PM.",
      "Perseguir clientes para que te paguen.",
    ],
    fix: "Hoys arregla las tres.",
  },
  two: {
    h2: "Hoys hace dos cosas por ti.",
    paidLabel: "Trabajos pagados",
    paidH3: "Trabajos que ya están pagados.",
    paidList: [
      "El cliente paga antes de que llegues.",
      "Un pro por trabajo. Nunca pagas por un lead.",
      "Ves lo que te llevas y decides si lo tomas o lo pasas.",
    ],
    admit: "ADMITE UN PRO",
    crewLabel: "Equipo de IA",
    crewH3: "Ayuda con la oficina, por texto o voz.",
    crewList: [
      "Contesta cuando tú no puedes y agenda el trabajo.",
      "Prepara cotizaciones con fotos, mueve tu día y pide piezas.",
      "Manda facturas y cobra lo pendiente en más de 30 idiomas.",
    ],
    note: "Funciona con los clientes que ya tienes.",
    noteFree: " Sin costo en tus propios trabajos.",
  },
  day: {
    h2: "Un día con Hoys",
    sub: "Escríbele o háblale como a alguien de tu equipo. Se encarga del resto.",
    biz: "Equipo de IA de Ramos Heating and Air",
    you: "Tú",
    replay: "Ver otra vez",
    roles: ["Contesta", "Cotiza", "Pide piezas", "Busca trabajos", "Reagenda", "Cobra"],
    msgs: {
      m1: "¡Buenos días! Tienes 4 trabajos hoy. Primero Maple St a las 8. Te mando la dirección.",
      m2: "Dana en Alder St necesita que revises su AC. No enfría. Está libre a las 3. ¿La agendo?",
      m3: "Agéndalo",
      s3: "AGENDADO 3 PM",
      m4: "¿Qué sigue?",
      m5: "Maple St, la calefacción no prende. Mandaron fotos—podría ser el encendedor. ¿Reviso si lo tienen en la tienda de repuestos?",
      m6: "Sí",
      s6: "EN STOCK · APARTADO PARA RECOGER",
      m7: "Tienes un hueco a la 1. Mantenimiento de AC a 2 millas. El cliente pagó $300. Te quedan $255. ¿Lo quieres?",
      m8: "Lo tomo",
      s8: "TRABAJO PAGADO AGENDADO",
      m9: "Voy atrasado. Mueve todo una hora.",
      m10: "Listo. Mantenimiento a las 2, Dana a las 4. Los dos dijeron que sí. Te mando las direcciones cuando estés listo.",
      m11: "Ya mandé las facturas. Les recordé a los Johnson lo de los $180. Por hoy terminaste—mañana temprano te mando los trabajos.",
      s11: "FACTURAS ENVIADAS",
    },
  },
  paid: {
    h2: "Trabajos pagados, no leads pagados.",
    rate: "La comisión empieza en 15%. Ves la cantidad exacta antes de aceptar.",
    job: "Mantenimiento de AC",
    when: "Jue 10 AM, a 2 millas",
    r1: "El cliente pagó primero",
    r2: "Hoys se queda (empieza en 15%)",
    tot: "Te llevas",
    take: "LO TOMO",
    pass: "PASO, SIN COSTO",
    cmpL: "Sitios de leads",
    cmpR: "Hoys",
    rows: [
      ["$35 a $200+ por lead", "$0 por adelantado"],
      ["El mismo lead va a varios pros", "Un pro por trabajo"],
      ["La mayoría nunca contesta", "El cliente ya pagó"],
      ["Pagas, ganes o pierdas", "Desde 15%, solo en trabajos terminados"],
    ],
    whereQ: "¿De dónde salen los trabajos pagados?",
    whereA:
      "Cada vez más gente le pide a asistentes de IA que les arreglen cosas en casa. Cuando lo hacen, Hoys agenda a un pro cercano, cobra primero y guarda el pago hasta que se termina el trabajo.",
  },
  how: {
    h2: "Cómo funciona",
    steps: [
      ["Únete a la lista", "Dinos dónde trabajas y qué haces."],
      ["Te configuramos por texto", "Unos 15 minutos cuando abra tu zona."],
      [
        "Empieza el equipo de IA. Luego llegan los trabajos pagados.",
        "Los pros fundadores reciben trabajos pagados primero.",
      ],
    ],
  },
  team: {
    h2: "Quién está detrás de Hoys",
    rishiRole: "Cofundador y CEO",
    rishi:
      "Construyó la plataforma tecnológica más grande de Asia para pequeños comerciantes: más de 100,000 tiendas. Respaldado por grandes inversionistas y los fundadores de DoorDash y Zoom.",
    satwikRole: "Cofundador y CTO",
    satwik:
      "Construyó sistemas de IA en Meta (Facebook). Doctorado de Carnegie Mellon. Antes trabajó en Google.",
  },
  spots: {
    h2: "Los lugares fundadores son limitados.",
    sub: "Los trabajos pagados abren ciudad por ciudad. Los pros fundadores los reciben primero.",
    taken: (t: number, c: number) => `${t} de ${c} tomados`,
    joined: (n: number) => `${n} pros se unieron`,
    full: "SOLO LISTA DE ESPERA",
    next: "Únete para el próximo grupo.",
    recent: "Se unieron hace poco",
    when: { today: "hoy", yesterday: "ayer", "this week": "esta semana" },
    defaultTrade: "Pro de servicios del hogar",
  },
  cities: {
    bay_area: "Bay Area",
    los_angeles: "Los Ángeles",
    new_york: "Nueva York",
    other: "Otro lugar",
  },
  citiesShort: {
    bay_area: "el Bay Area",
    los_angeles: "LA",
    new_york: "Nueva York",
    other: "tu zona",
  },
  final: { h2: "Trabajos pagados y un equipo de IA. Gratis para unirte." },
  footer: { questions: "¿Preguntas?", text: "Texto" },
  sheet: {
    workOrder: "ORDEN DE TRABAJO",
    close: "Cerrar",
    h: "Únete a la lista",
    hSub: "Trabajos pagados sin pagar por leads.",
    where: "¿Dónde trabajas?",
    name: "Tu nombre",
    namePh: "Nombre y apellido",
    phone: "Número de celular",
    otherCity: "Tu ciudad",
    otherCityPh: "Ciudad, estado",
    consentBold: "Acepto que Hoys me mande textos o llame sobre la lista de espera.",
    saving: "Guardando...",
    errCity: "Escoge dónde trabajas.",
    errName: "Pon tu nombre.",
    errPhone: "Ese número no se ve bien.",
    errOtherCity: "Añade la ciudad donde trabajas.",
    errConsent: "Marca la casilla para poder mandarte textos.",
    errNet: "No se pudo enviar. Revisa tu señal y vuelve a intentar.",
    s2h: "Un último paso.",
    s2sub: "Dinos qué tipo de trabajo haces y luego únete a la lista.",
    trades: "Tus oficios",
    tradeLabels: {
      plumbing: "Plomería",
      electrical: "Electricidad",
      hvac: "HVAC",
      handyman: "Handyman",
      roofing: "Techos",
      general_contractor: "Contratista general",
      cleaning: "Limpieza",
      other: "Otro",
    },
    whichTrade: "¿Cuál oficio?",
    crew: "Tamaño del equipo",
    crewLabels: {
      just_me: "Solo yo",
      "2_5": "2 a 5",
      "6_10": "6 a 10",
      "10_plus": "Más de 10",
    },
    zip: "Código postal",
    biz: "Nombre del negocio (opcional)",
    email: "Email (opcional)",
    errZip: "El código postal tiene 5 dígitos.",
    errEmail: "Ese email no se ve bien.",
    save: "Únete a la lista",
    onList: "EN LA LISTA",
    inCity: (c: string) => `en ${c}`,
    onTheList: "en la lista",
    step1: "Te mandamos un texto para confirmar.",
    step2: (c: string) => `Cuando abra ${c}, te configuramos por texto. Unos 15 minutos.`,
    step3: "Los pros fundadores reciben trabajos pagados primero.",
    knowPro: "¿Conoces a un pro cansado de pagar por leads?",
    share: "Compartir link",
    copy: "Copiar link",
    copied: "Copiado",
    shareText: "Hoys manda trabajos pagados a pros. Sin pagar por leads. Únete a la lista:",
    bump: (n: number) => `Cada pro que se une con tu link te sube ${n} lugares.`,
    call: "¿Quieres una llamada rápida con nuestro equipo?",
    callBtn: "Sí, llámenme",
    callDone: "Listo. Alguien de Hoys te va a llamar.",
  },
  consentText: "Hoys me puede mandar textos o llamar sobre la lista de espera.",
};

export const dicts: Record<Lang, Dict> = { en, es };
